-- Alterar o caminho do datafile para o local padrao do banco
CREATE TABLESPACE @TS_NAME@
  DATAFILE '@TS_DATAFILE@' SIZE @TS_SIZE@
  AUTOEXTEND ON
  MAXSIZE @TS_MAXSIZE@
  LOGGING
  ONLINE
  PERMANENT
  BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL
  AUTOALLOCATE DEFAULT
  NOCOMPRESS
  SEGMENT SPACE MANAGEMENT AUTO;
QUIT;
