CREATE USER @SCHEMA@ IDENTIFIED BY @SENHA@
DEFAULT TABLESPACE @TS_NAME@
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT,RESOURCE TO @SCHEMA@;
GRANT SELECT ON GV_$SESSION TO @SCHEMA@;
GRANT SELECT ON GV_$SESSTAT TO @SCHEMA@;
GRANT SELECT ON GV_$SYSSTAT TO @SCHEMA@;
GRANT SELECT ON GV_$SYS_TIME_MODEL TO @SCHEMA@;
GRANT SELECT ON V_$SESSION TO @SCHEMA@;
GRANT SELECT ON V_$SESSTAT TO @SCHEMA@;
GRANT SELECT ON V_$SYSSTAT TO @SCHEMA@;
GRANT SELECT ON V_$SYS_TIME_MODEL TO @SCHEMA@;
GRANT SELECT ON V_$MYSTAT TO @SCHEMA@;
GRANT EXECUTE ON DBMS_LOCK TO @SCHEMA@;
GRANT CREATE PUBLIC SYNONYM TO @SCHEMA@;
-- Precisa deste para criar a trigger de logoff.
-- Fazer um REVOKE assim que terminar o processo de instalacao
GRANT DBA TO @SCHEMA@;
QUIT;
