-- TDW_ESTATISTICAS_RAC: contem as estatisticas sumarizadas por programa, por dia.

CREATE PUBLIC SYNONYM TDW_ESTATISTICAS_RAC FOR @SCHEMA@.TDW_ESTATISTICAS_RAC;

CREATE TABLE TDW_ESTATISTICAS_RAC (
  PROGRAM           VARCHAR2(64) NOT NULL,
  TIMESTAMP         DATE NOT NULL,
  ANUM_ESTATISTICA  NUMBER NOT NULL,
  ACOD_ESTATISTICA  CHAR(1),
  VALUE             NUMBER
) TABLESPACE @TS_NAME@;
QUIT;
