-- Classes utilizadas em GV$SYSSTAT
CREATE PUBLIC SYNONYM TTIPO_ESTATISTICA_CLASSES FOR @SCHEMA@.TTIPO_ESTATISTICA_CLASSES;
CREATE TABLE TTIPO_ESTATISTICA_CLASSES (
  ACOD_CLASSE   NUMBER NOT NULL,
  ANOM_CLASSE   VARCHAR2(64)
) TABLESPACE @TS_NAME@;

INSERT INTO TTIPO_ESTATISTICA_CLASSES VALUES (1, 'User');
INSERT INTO TTIPO_ESTATISTICA_CLASSES VALUES (2, 'Redo');
INSERT INTO TTIPO_ESTATISTICA_CLASSES VALUES (4, 'Enqueue');
INSERT INTO TTIPO_ESTATISTICA_CLASSES VALUES (8, 'Cache');
INSERT INTO TTIPO_ESTATISTICA_CLASSES VALUES (16, 'SO');
INSERT INTO TTIPO_ESTATISTICA_CLASSES VALUES (32, 'RAC');
INSERT INTO TTIPO_ESTATISTICA_CLASSES VALUES (64, 'SQL');
INSERT INTO TTIPO_ESTATISTICA_CLASSES VALUES (128, 'Debug');
COMMIT;
QUIT;
