-- Tabela que guarda as descricoes de V$SYS_TIME_MODEL
CREATE PUBLIC SYNONYM TTIPO_ESTATISTICA_TIME_MODEL FOR @SCHEMA@.TTIPO_ESTATISTICA_TIME_MODEL;

-- Tabela auxiliar para guardar as descrições dos valores de GV$SYS_TIME_MODEL
-- Se mais pra frente for necessário, incluir o atributo de descrição
CREATE TABLE TTIPO_ESTATISTICA_TIME_MODEL (
  STAT_ID   NUMBER,
  STAT_NAME VARCHAR2(64)
) TABLESPACE @TS_NAME@;

INSERT INTO TTIPO_ESTATISTICA_TIME_MODEL 
  SELECT DISTINCT STAT_ID, STAT_NAME FROM GV$SYS_TIME_MODEL;
COMMIT;
QUIT;
