-- Tabela para guardar os valores de GV$SYS_TIME_MODEL

CREATE PUBLIC SYNONYM TESTATISTICAS_SYS_TIME_MODEL FOR @SCHEMA@.TESTATISTICAS_SYS_TIME_MODEL;

CREATE TABLE TESTATISTICAS_SYS_TIME_MODEL AS
  SELECT INST_ID, STAT_ID, VALUE, SYSDATE AS TIMESTAMP
  FROM GV$SYS_TIME_MODEL
  WHERE 1=2;
  
ALTER TABLE TESTATISTICAS_SYS_TIME_MODEL MOVE TABLESPACE @TS_NAME@

QUIT;
