CREATE PUBLIC SYNONYM TESTATISTICAS_DISKGROUPS FOR @SCHEMA@.TESTATISTICAS_DISKGROUPS;

CREATE TABLE TESTATISTICAS_DISKGROUPS (
  NAME        VARCHAR2(30) NOT NULL,
  TIMESTAMP   DATE NOT NULL,
  TOTAL_MB    NUMBER,
  FREE_MB     NUMBER,
  STATE       VARCHAR2(11)
) TABLESPACE @TS_NAME@;
QUIT;
