-- TABLESPACE utilizada para armazenamento das estatisticas: TS_ESTATISTICAS
-- SCHEMA: ABD7
-- ALTERAR ESSES PARAMETROS NO ARQUIVO CASO SEJA NECESSARIO OUTROS VALORES

-- Tabela utilizada para guardar os dados de acesso de objetos do Oracle
-- (tabelas, indices e LOBs). Busca os dados da GV$SEGMENT_STATISTICS
-- OWNER: Dono da tabela/indice/LOB
-- OBJECT_NAME: Nome do objeto
-- TABLESPACE_NAME: Tablespace onde esta o objeto
-- OBJECT_TYPE: Tipo (TABLE/INDEX/LOB)
-- TIMESTAMP: Horario da coleta de estatistica do objeto
-- VALUE: Valor da soma da estatistica das instancias no tempo da coleta
-- STATISTIC_NAME: Podia estar em outra tabela na forma normal, mas nao esta!!
-- STATISTIC#: Identificador da estatistica para a GV$SEGMENT_STATISTICS

-- Estatisticas coletadas:
-- logical reads, db block changes, physical reads, 
-- physical writes, space used, space allocated, segment scans

CREATE PUBLIC SYNONYM TESTATISTICAS_SEGMENTOS FOR @SCHEMA@.TESTATISTICAS_SEGMENTOS;

CREATE TABLE TESTATISTICAS_SEGMENTOS (
  OWNER VARCHAR2(30),
  OBJECT_NAME VARCHAR2(30),
  SUBOBJECT_NAME VARCHAR2(30),
  TABLESPACE_NAME VARCHAR2(30),
  OBJECT_TYPE VARCHAR2(18),
  TIMESTAMP DATE,
  VALUE NUMBER,
  STATISTIC_NAME VARCHAR2(64),
  STATISTIC# NUMBER
) TABLESPACE @TS_NAME@;

-- Essa vista busca os "deltas" entre as coletas
-- Agrupados 
-- Obviamente, o primeiro "delta" eh nulo/0

CREATE PUBLIC SYNONYM VESTATISTICAS_SEGMENTOS_RELAT FOR @SCHEMA@.VESTATISTICAS_SEGMENTOS_RELAT;

CREATE OR REPLACE VIEW VESTATISTICAS_SEGMENTOS_RELAT AS 
SELECT OWNER, 
  OBJECT_NAME, 
  OBJECT_TYPE, 
  STATISTIC#, 
  STATISTIC_NAME, 
  TIMESTAMP, 
  CASE WHEN DELTA < 0 THEN 0 ELSE DELTA END AS DELTA FROM (
    SELECT OWNER, 
    OBJECT_NAME, 
    OBJECT_TYPE, 
    STATISTIC#, 
    STATISTIC_NAME,
    TIMESTAMP, 
    VALUE,
    LAG(VALUE) OVER (PARTITION BY OWNER, OBJECT_NAME, OBJECT_TYPE, STATISTIC# ORDER BY TIMESTAMP) AS LAST,
    VALUE - LAG(VALUE) OVER (PARTITION BY OWNER, OBJECT_NAME, OBJECT_TYPE, STATISTIC# ORDER BY TIMESTAMP) AS DELTA
  FROM TESTATISTICAS_SEGMENTOS
  ORDER BY OWNER, OBJECT_TYPE, OBJECT_NAME, STATISTIC#, TIMESTAMP)
;

-- Exibe a soma dos deltas para a data atual

CREATE PUBLIC SYNONYM VSUMARIO_STAT_SEGMENTOS FOR @SCHEMA@.VSUMARIO_STAT_SEGMENTOS;

CREATE OR REPLACE VIEW  VSUMARIO_STAT_SEGMENTOS AS 
SELECT OWNER, OBJECT_NAME, MIN(TIMESTAMP) FIRST, MAX(TIMESTAMP) LAST, SUM(DELTA) AS TOTAL
FROM VESTATISTICAS_SEGMENTOS_RELAT 
WHERE 
  OBJECT_TYPE NOT IN ('INDEX', 'LOB')
  AND TIMESTAMP >= TRUNC(SYSDATE)
GROUP BY (OWNER, OBJECT_NAME)
ORDER BY TOTAL DESC;

QUIT;
