-- Dar acesso aos usuarios que podem consultar as tabelas de estatisticas
-- CREATE ROLE GTO_ESTATISTICAS;
-- GRANT SELECT ON TESTATISTICAS_RAC TO GTO_ESTATISTICAS;
-- GRANT SELECT ON TESTATISTICAS_RAC_TMP TO GTO_ESTATISTICAS;
-- GRANT SELECT ON TESTATISTICAS_EVENTOS TO GTO_ESTATISTICAS;
-- GRANT SELECT ON TTIPO_ESTATISTICA_RAC TO GTO_ESTATISTICAS;
-- GRANT SELECT ON TDW_ESTATISTICAS_RAC TO GTO_ESTATISTICAS;
-- GRANT GTO_ESTATISTICAS TO M23360;
QUIT;
