-- Objetos de banco que podem ter sido criados previamente.
-- Comentar o quit somente se houver certeza que os objetos
-- podem ser mesmo removidos.
-- QUIT;
DROP PROCEDURE ABD7.PROGASTOSESTATISTICANOPERIODO;
DROP PROCEDURE ABD7.PROSETANOMEMODULO;
DROP PROCEDURE ABD7.PRO_TOTAIS_ESTATISTICAS_RAC;
DROP TRIGGER   ABD7.TRG_LOGOFF;
DROP TABLE ABD7.TDW_ESTATISTICAS_RAC;
DROP TABLE ABD7.TESTATISTICAS_DISKGROUPS;
DROP TABLE ABD7.TESTATISTICAS_EVENTOS;
DROP TABLE ABD7.TESTATISTICAS_EVENTOS;
DROP TABLE ABD7.TESTATISTICAS_RAC;
DROP TABLE ABD7.TESTATISTICAS_RAC_TMP;
DROP TABLE ABD7.TESTATISTICAS_SYSSTAT;
DROP TABLE ABD7.TESTATISTICAS_SYS_TIME_MODEL;
DROP TABLE ABD7.TTIPO_ESTATISTICA_CLASSES;
DROP TABLE ABD7.TTIPO_ESTATISTICA_RAC;
DROP TABLE ABD7.TTIPO_ESTATISTICA_RAC;
DROP TABLE ABD7.TTIPO_ESTATISTICA_SYSSTAT;
DROP TABLE ABD7.TTIPO_ESTATISTICA_TIME_MODEL;
